<?php

namespace Modules\Ecommerce\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EcommerceDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $blogs = DB::table('blogs')->count();
        if (!$blogs) {
            DB::table('blogs')->insert([
                [
                    'id' => 2,
                    'user_id' => 1,
                    'slug' => 'sell-online-with-ecommerce-addon-for-pos',
                    'title' => 'Sell online with eCommerce add-on for POS',
                    'description' => '<p><a href=\"https://codecanyon.net/item/lims-stock-manager-pro-with-pos/22256829\" target=\"_blank\" rel=\"noopener\">Buy POS</a> Unleash the potential of your offline business with <strong>eCommerce add-on for POS</strong>. Leverage the power of eCommerce alongside your existing shop setup. Connect and manage both your offline POS and online eCommerce store from within one simple, yet powerful admin panel. Our eCommerce add-on offers all the options available in any comparable eCommerce php script, if not more. From dynamic menus, pages, collections to sliders, page widgets, drag &amp; drop layout builder; it has it all. We are committed to bring in more features to make it the best option for eCommerce php script. eCommerce add-on along with POS will help you realize the true potential of your multichannel business.</p>',
                    'thumbnail' => 'thumb_20240416021052.png',
                    'youtube' => null,
                    'meta_title' => 'Sell online with eCommerce add-on for POS',
                    'meta_description' => 'Sell online with eCommerce add-on for POS',
                    'og_title' => 'Sell online with eCommerce add-on for POS',
                    'og_image' => null,
                    'og_description' => 'Sell online with eCommerce add-on for POS',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'user_id' => 1,
                    'slug' => 'how-ecommerce-compliments-your-offline-sales',
                    'title' => 'How eCommerce compliments your offline sales',
                    'description' => '<p><a href=\"https://codecanyon.net/item/lims-stock-manager-pro-with-pos/22256829\" target=\"_blank\" rel=\"noopener\">Buy POS</a> Unleash the potential of your offline business with <strong>eCommerce add-on for POS</strong>. Leverage the power of eCommerce alongside your existing shop setup. Connect and manage both your offline POS and online eCommerce store from within one simple, yet powerful admin panel. Our eCommerce add-on offers all the options available in any comparable eCommerce php script, if not more. From dynamic menus, pages, collections to sliders, page widgets, drag &amp; drop layout builder; it has it all. We are committed to bring in more features to make it the best option for eCommerce php script. eCommerce add-on along with POS will help you realize the true potential of your multichannel business.</p>',
                    'thumbnail' => 'thumb_20240416021810.jpg',
                    'youtube' => null,
                    'meta_title' => 'Sell online with eCommerce add-on for POS',
                    'meta_description' => 'Sell online with eCommerce add-on for POS',
                    'og_title' => 'Sell online with eCommerce add-on for POS',
                    'og_image' => null,
                    'og_description' => 'Sell online with eCommerce add-on for POS',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'user_id' => 1,
                    'slug' => 'why-you-should-sell-online-in-2024',
                    'title' => 'Why you should sell online in 2024',
                    'description' => '<p>Why you should sell online in 2024</p>',
                    'thumbnail' => 'thumb_20240416022755.jpg',
                    'youtube' => null,
                    'meta_title' => 'Why you should sell online in 2024',
                    'meta_description' => 'Why you should sell online in 2024',
                    'og_title' => 'Why you should sell online in 2024',
                    'og_image' => null,
                    'og_description' => 'Why you should sell online in 2024',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
        }

        $collections = DB::table('collections')->count();
        if (!$collections) {
            DB::table('collections')->insert([
                [
                    'id' => 1,
                    'name' => 'New Products',
                    'image' => null,
                    'page_title' => 'New Products at eCommerce',
                    'short_description' => 'New Products at eCommerce',
                    'slug' => 'new-products',
                    'products' => '3,11,12,13,16,17,19,20',
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'name' => 'Sale',
                    'image' => null,
                    'page_title' => 'Products on Sale',
                    'short_description' => 'Products on Sale',
                    'slug' => 'sale',
                    'products' => '1,2,11,21',
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
        }

        $customerAddresses = DB::table('customer_addresses')->count();
        if (!$customerAddresses) {
            DB::table('customer_addresses')->insert([
                [
                    'id' => 1,
                    'name' => 'Test Customer',
                    'phone' => '0000-0000-0000',
                    'email' => null,
                    'address' => 'Road 01, Block-C, area, test road',
                    'city' => 'Test City',
                    'state' => '',
                    'country' => 'Bangladesh',
                    'zip' => '4000',
                    'default' => 1,
                    'customer_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'name' => 'mehmet',
                    'phone' => '(518) 484 3470',
                    'email' => null,
                    'address' => 'SADAS',
                    'city' => 'DASD',
                    'state' => 'ASD',
                    'country' => 'ASDAS',
                    'zip' => 'DASD',
                    'default' => 0,
                    'customer_id' => 51,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'name' => 'DASD',
                    'phone' => 'ASDA',
                    'email' => null,
                    'address' => 'SDASD',
                    'city' => 'ASD',
                    'state' => 'ASDAS',
                    'country' => 'DASD',
                    'zip' => 'ASD',
                    'default' => 0,
                    'customer_id' => 51,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'name' => 'wwww',
                    'phone' => '222222',
                    'email' => null,
                    'address' => '2222',
                    'city' => '222',
                    'state' => '2222',
                    'country' => '22222',
                    'zip' => '222222222',
                    'default' => 1,
                    'customer_id' => 99,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'name' => 'USA',
                    'phone' => '4174544',
                    'email' => null,
                    'address' => 'MIAMI',
                    'city' => 'MIAMI',
                    'state' => 'UE',
                    'country' => 'MI',
                    'zip' => '88504',
                    'default' => 0,
                    'customer_id' => 109,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 6,
                    'name' => 'HDHDSHH',
                    'phone' => '43435',
                    'email' => null,
                    'address' => 'FGFGFG',
                    'city' => 'FDGFDG',
                    'state' => 'GS',
                    'country' => 'SG',
                    'zip' => '4454',
                    'default' => 1,
                    'customer_id' => 109,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
        }

        $ecommerceSettings = DB::table('ecommerce_settings')->count();
        if (!$ecommerceSettings) {
            DB::table('ecommerce_settings')->insert([
                'id' => 1,
                'site_title' => 'Ecommerce',
                'theme' => 'default',
                'theme_font' => 'Inter',
                'theme_color' => '#fa9928',
                'logo' => DB::table('general_settings')->value('site_logo'),
                'favicon' => 'favicon.png',
                'store_phone' => '0000-0000-0000',
                'store_email' => 'support@yoursite.com',
                'store_address' => 'Queen St, Cardiff, UK',
                'home_page' => 4,
                'is_rtl' => 0,
                'search' => 0,
                'warehouse_id' => 1,
                'biller_id' => 1,
                'contact_form_email' => 'support@yoursite.com',
                'free_shipping_from' => 2000,
                'flat_rate_shipping' => 50,
                'checkout_pages' => json_encode([5, 6]), // Using JSON encoding for array
                'gift_card' => 0,
                'custom_css' => null,
                'custom_js' => null,
                'chat_code' => null,
                'analytics_code' => null,
                'fb_pixel_code' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }

        $faqs = DB::table('faqs')->count();
        if (!$faqs) {
            DB::table('faqs')->insert([
                [
                    'id' => 1,
                    'question' => 'What Shipping Methods Are Available?',
                    'answer' => 'You can avail flat rate shipping, region & weight based shipping methods while shopping with eCommerce',
                    'category_id' => 1,
                    'order' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'question' => 'Do You Ship Internationally?',
                    'answer' => 'We have plans to initiate international shipping in near future',
                    'category_id' => 1,
                    'order' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'question' => 'How Long Will It Take To Get My Product?',
                    'answer' => 'It usually takes between 3-5 business days. It may take longer in holiday season though',
                    'category_id' => 1,
                    'order' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'question' => 'Is Buying Online Safe?',
                    'answer' => 'Our payment system is fully safe and secure.',
                    'category_id' => 2,
                    'order' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'question' => 'What Payment Methods Are Accepted?',
                    'answer' => 'We accept PayPal, Stripe, Cash on delivery etc. New payment methods will be added in future.',
                    'category_id' => 2,
                    'order' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 6,
                    'question' => 'How do I place an Order?',
                    'answer' => 'You can place order without an account as well',
                    'category_id' => 3,
                    'order' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
        }

        $faqCategories = DB::table('faq_categories')->count();
        if (!$faqCategories) {
            DB::table('faq_categories')->insert([
                [
                    'id' => 1,
                    'name' => 'Shipping',
                    'order' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'name' => 'Payment',
                    'order' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'name' => 'Order & Returns',
                    'order' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
        }

        $menus = DB::table('menus')->count();
        if (!$menus) {
            DB::table('menus')->insert([
                [
                    'id' => 1,
                    'title' => 'Main Nav',
                    'location' => '1',
                    'content' => '[[{"id":"16"},{"id":"4"},{"id":"2"},{"id":"22"},{"id":"1"}]]',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'title' => 'footer menu 1',
                    'location' => '0',
                    'content' => '[[{"id":"9"},{"id":"8"},{"id":"7"},{"id":"6"}]]',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'title' => 'footer menu 2',
                    'location' => '0',
                    'content' => '[[{"id":"10"},{"id":"11"},{"id":"12"}]]',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'title' => 'footer menu 3',
                    'location' => '0',
                    'content' => '[[{"id":"13"},{"id":"14"},{"id":"15"}]]',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
        }

        $menuItems = DB::table('menu_items')->count();
        if (!$menuItems) {
            DB::table('menu_items')->insert([
                ['id' => 1, 'title' => 'Contact Us', 'name' => NULL, 'slug' => 'contact-us', 'type' => 'page', 'target' => NULL, 'menu_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 2, 'title' => 'FAQ', 'name' => NULL, 'slug' => 'faq', 'type' => 'page', 'target' => NULL, 'menu_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 4, 'title' => 'Laptops & Computers', 'name' => NULL, 'slug' => 'laptops-computers', 'type' => 'category', 'target' => NULL, 'menu_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 6, 'title' => 'Contact Us', 'name' => NULL, 'slug' => 'contact-us', 'type' => 'page', 'target' => NULL, 'menu_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 7, 'title' => 'FAQ', 'name' => NULL, 'slug' => 'faq', 'type' => 'page', 'target' => NULL, 'menu_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 8, 'title' => 'Privacy Policy', 'name' => NULL, 'slug' => 'privacy-policy', 'type' => 'page', 'target' => NULL, 'menu_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 9, 'title' => 'Terms & Conditions', 'name' => NULL, 'slug' => 'terms-conditions', 'type' => 'page', 'target' => NULL, 'menu_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 10, 'title' => 'About eCommerce', 'name' => 'About Us', 'slug' => 'about-ecommerce', 'type' => 'page', 'target' => NULL, 'menu_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 11, 'title' => 'Contact Us', 'name' => NULL, 'slug' => 'contact-us', 'type' => 'page', 'target' => NULL, 'menu_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 12, 'title' => 'FAQ', 'name' => NULL, 'slug' => 'faq', 'type' => 'page', 'target' => NULL, 'menu_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 13, 'title' => 'My Account', 'name' => NULL, 'slug' => 'yoursite.com', 'type' => 'custom', 'target' => NULL, 'menu_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 14, 'title' => 'Cart', 'name' => NULL, 'slug' => 'yoursite.com', 'type' => 'custom', 'target' => NULL, 'menu_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 15, 'title' => 'Shop', 'name' => NULL, 'slug' => 'yoursite.com', 'type' => 'custom', 'target' => NULL, 'menu_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 16, 'title' => 'Home', 'name' => NULL, 'slug' => 'home', 'type' => 'page', 'target' => NULL, 'menu_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                ['id' => 22, 'title' => 'Blog', 'name' => 'Blog', 'slug' => '#', 'type' => 'custom', 'target' => NULL, 'menu_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ]);
        }

        $newsletter = DB::table('newsletter')->count();
        if (!$newsletter) {
            DB::table('newsletter')->insert([
                [
                    'id' => 1,
                    'email' => 'admin@demo.com',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'email' => 'student@spagreen.net',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'email' => 'ssd@gmail.com',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
        }

        $pages = DB::table('pages')->count();
        if (!$pages) {
            DB::table('pages')->insert([
                [
                    'id' => 1,
                    'page_name' => 'About eCommerce',
                    'description' => '<p>eCommerce is an optional premium add-on/extension/module for POS. If you have shop where you are running or plan to run our POS software and you want to sell online as well, this is the perfect solution for you. Whether you are looking to go for a local, nation-wide or even international operation with your eCommerce store, eCommerce has everything built-in to meet all the challenges therein.</p>',
                    'slug' => 'about-ecommerce',
                    'meta_title' => 'eCommerce',
                    'meta_description' => 'eCommerce is an optional premium add-on/extension/module for POS.',
                    'og_title' => 'eCommerce',
                    'og_image' => null,
                    'og_description' => null,
                    'template' => 'default',
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'page_name' => 'Contact Us',
                    'description' => null,
                    'slug' => 'contact-us',
                    'meta_title' => '',
                    'meta_description' => '',
                    'og_title' => '',
                    'og_image' => null,
                    'og_description' => null,
                    'template' => 'contact',
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'page_name' => 'FAQ',
                    'description' => null,
                    'slug' => 'faq',
                    'meta_title' => 'Frequently Asked Questions | eCommerce FAQ',
                    'meta_description' => 'Frequently Asked Questions | eCommerce FAQ',
                    'og_title' => null,
                    'og_image' => null,
                    'og_description' => null,
                    'template' => 'faq',
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'page_name' => 'Home',
                    'description' => '<p>eCommerce is an optional premium add-on/extension/module for POS. If you have shop where you are running or plan to run our POS software and you want to sell online as well, this is the perfect solution for you. Whether you are looking to go for a local, nation-wide or even international operation with your eCommerce store, eCommerce has everything built-in to meet all the challenges therein.</p>',
                    'slug' => 'home',
                    'meta_title' => 'eCommerce add-on for POS, inventory management Laravel application',
                    'meta_description' => 'eCommerce is an optional premium add-on/extension/module for POS.',
                    'og_title' => 'eCommerce',
                    'og_image' => null,
                    'og_description' => null,
                    'template' => 'home',
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'page_name' => 'Privacy Policy',
                    'description' => '<p>Quisque varius diam vel metus mattis, id aliquam diam rhoncus. Proin vitae magna in dui finibus malesuada et at nulla. Morbi elit ex, viverra vitae ante vel, blandit feugiat ligula. Fusce fermentum iaculis nibh, at sodales leo maximus a. Nullam ultricies sodales nunc, in pellentesque lorem mattis quis...</p>',
                    'slug' => 'privacy-policy',
                    'meta_title' => null,
                    'meta_description' => null,
                    'og_title' => null,
                    'og_image' => null,
                    'og_description' => null,
                    'template' => 'default',
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 6,
                    'page_name' => 'Terms & Conditions',
                    'description' => '<p>Quisque varius diam vel metus mattis, id aliquam diam rhoncus. Proin vitae magna in dui finibus malesuada et at nulla. Morbi elit ex, viverra vitae ante vel, blandit feugiat ligula. Fusce fermentum iaculis nibh, at sodales leo maximus a. Nullam ultricies sodales nunc, in pellentesque lorem mattis quis...</p>',
                    'slug' => 'terms-conditions',
                    'meta_title' => null,
                    'meta_description' => null,
                    'og_title' => null,
                    'og_image' => null,
                    'og_description' => null,
                    'template' => 'default',
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
        }

        $pageWidgets = DB::table('page_widgets')->count();
        if (!$pageWidgets) {
            DB::table('page_widgets')->insert([
                [
                    'id' => 1,
                    'name' => 'brand-slider-widget',
                    'page_id' => 4,
                    'order' => 6,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => '1,2,3,4,5,6,7,8',
                    'brand_slider_title' => 'Browse By Brands',
                    'brand_slider_loop' => 'yes',
                    'brand_slider_autoplay' => 'yes',
                    'brand_slider_ids' => '1,2,3,4,5,6,7,8',
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'name' => 'product-category-widget',
                    'page_id' => 4,
                    'order' => 1,
                    'product_category_title' => 'Laptops for everyday',
                    'product_category_id' => 6,
                    'product_category_type' => 'gallery',
                    'product_category_slider_loop' => 'true',
                    'product_category_slider_autoplay' => 'yes',
                    'product_category_limit' => '10',
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'name' => 'category-slider-widget',
                    'page_id' => 4,
                    'order' => 0,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => 'Browse By categories',
                    'category_slider_loop' => 'yes',
                    'category_slider_autoplay' => 'yes',
                    'category_slider_ids' => '1,6,12,17,23,29,30,33',
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'name' => 'product-collection-widget',
                    'page_id' => 4,
                    'order' => 5,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => 'New In Town',
                    'product_collection_id' => '1',
                    'product_collection_type' => 'slider',
                    'product_collection_slider_loop' => 'true',
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => '10',
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 13,
                    'name' => 'category-slider-widget',
                    'page_id' => 8,
                    'order' => 1,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => 'test2',
                    'category_slider_loop' => 'yes',
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => '1,6,12',
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 14,
                    'name' => 'brand-slider-widget',
                    'page_id' => 8,
                    'order' => 0,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => 'Browse By Brands',
                    'brand_slider_loop' => 'no',
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => '1,2,3,4',
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 19,
                    'name' => 'brand-slider-widget',
                    'page_id' => 13,
                    'order' => 0,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => 'Browse By Brands',
                    'brand_slider_loop' => 'yes',
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => '1,2,3',
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 20,
                    'name' => 'text-widget',
                    'page_id' => 13,
                    'order' => 1,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => 'ecommerce',
                    'text_content' => '<p>njnkjnk nnj</p>',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 30,
                    'name' => 'product-collection-widget',
                    'page_id' => 4,
                    'order' => 2,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => 'New In Town',
                    'product_collection_id' => '1',
                    'product_collection_type' => 'gallery',
                    'product_collection_slider_loop' => 'true',
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => '10',
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 31,
                    'name' => 'text-widget',
                    'page_id' => 1,
                    'order' => 0,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 32,
                    'name' => 'product-category-widget',
                    'page_id' => 4,
                    'order' => 3,
                    'product_category_title' => 'Smartphones & Gadgets',
                    'product_category_id' => '1',
                    'product_category_type' => 'gallery',
                    'product_category_slider_loop' => 'true',
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => '10',
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 33,
                    'name' => 'three-c-banner-widget',
                    'page_id' => 4,
                    'order' => 4,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 34,
                    'name' => 'brand-slider-widget',
                    'page_id' => 4,
                    'order' => 7,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => 'yes',
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 35,
                    'name' => 'two-c-banner-widget',
                    'page_id' => 4,
                    'order' => 8,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 36,
                    'name' => 'tab-product-collection-widget',
                    'page_id' => 4,
                    'order' => 9,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => 'gallery',
                    'tab_product_collection_slider_loop' => 'true',
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => '10',
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 37,
                    'name' => 'brand-slider-widget',
                    'page_id' => 4,
                    'order' => 10,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => 'yes',
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 38,
                    'name' => 'text-widget',
                    'page_id' => 4,
                    'order' => 11,
                    'product_category_title' => null,
                    'product_category_id' => null,
                    'product_category_type' => null,
                    'product_category_slider_loop' => null,
                    'product_category_slider_autoplay' => null,
                    'product_category_limit' => null,
                    'tab_product_collection_id' => null,
                    'tab_product_collection_type' => null,
                    'tab_product_collection_slider_loop' => null,
                    'tab_product_collection_slider_autoplay' => null,
                    'tab_product_collection_limit' => null,
                    'product_collection_title' => null,
                    'product_collection_id' => null,
                    'product_collection_type' => null,
                    'product_collection_slider_loop' => null,
                    'product_collection_slider_autoplay' => null,
                    'product_collection_limit' => null,
                    'category_slider_title' => null,
                    'category_slider_loop' => null,
                    'category_slider_autoplay' => null,
                    'category_slider_ids' => null,
                    'brand_slider_title' => null,
                    'brand_slider_loop' => null,
                    'brand_slider_autoplay' => null,
                    'brand_slider_ids' => null,
                    'three_c_banner_link1' => null,
                    'three_c_banner_image1' => null,
                    'three_c_banner_link2' => null,
                    'three_c_banner_image2' => null,
                    'three_c_banner_link3' => null,
                    'three_c_banner_image3' => null,
                    'two_c_banner_link1' => null,
                    'two_c_banner_image1' => null,
                    'two_c_banner_link2' => null,
                    'two_c_banner_image2' => null,
                    'one_c_banner_link1' => null,
                    'one_c_banner_image1' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            ]);
        }

        $sliders = DB::table('sliders')->count();
        if (!$sliders) {
            DB::table('sliders')->insert([
                [
                    'id' => 3,
                    'title' => NULL,
                    'link' => NULL,
                    'image1' => '3.jpg',
                    'image2' => NULL,
                    'image3' => NULL,
                    'order' => 1,
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 7,
                    'title' => NULL,
                    'link' => NULL,
                    'image1' => '7.jpg',
                    'image2' => NULL,
                    'image3' => NULL,
                    'order' => 1,
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 8,
                    'title' => NULL,
                    'link' => NULL,
                    'image1' => '8.jpg',
                    'image2' => NULL,
                    'image3' => NULL,
                    'order' => 2,
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 12,
                    'title' => NULL,
                    'link' => NULL,
                    'image1' => '12.jpg',
                    'image2' => NULL,
                    'image3' => NULL,
                    'order' => 0,
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 14,
                    'title' => NULL,
                    'link' => NULL,
                    'image1' => '14.jpg',
                    'image2' => NULL,
                    'image3' => NULL,
                    'order' => 1,
                    'status' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            ]);
        }

        $socialLinks = DB::table('social_links')->count();
        if (!$socialLinks) {
            DB::table('social_links')->insert([
                [
                    'id' => 1,
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" height="16" width="10" viewBox="0 0 320 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M80 299.3V512H196V299.3h86.5l18-97.8H196V166.9c0-51.7 20.3-71.5 72.7-71.5c16.3 0 29.4 .4 37 1.2V7.9C291.4 4 256.4 0 236.2 0C129.3 0 80 50.5 80 159.4v42.1H14v97.8H80z"/></svg>',
                    'title' => 'Facebook',
                    'link' => 'https://www.facebook.com',
                    'order' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/></svg>',
                    'title' => 'Twitter',
                    'link' => 'https://twitter.com',
                    'order' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/></svg>',
                    'title' => 'Instagram',
                    'link' => 'https://instagram.com',
                    'order' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            ]);
        }

        $widgets = DB::table('widgets')->count();
        if (!$widgets) {
            DB::table('widgets')->insert([
                [
                    'id' => 1,
                    'name' => 'site-features-widget',
                    'location' => 'footer_top',
                    'order' => 0,
                    'feature_title' => 'Free Shipping',
                    'feature_secondary_title' => 'Free shipping on all orders over $200',
                    'feature_icon' => '202401150154290.png',
                    'site_info_name' => null,
                    'site_info_description' => null,
                    'site_info_address' => null,
                    'site_info_phone' => null,
                    'site_info_email' => null,
                    'site_info_hours' => null,
                    'newsletter_title' => null,
                    'newsletter_text' => null,
                    'quick_links_title' => null,
                    'quick_links_menu' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'name' => 'site-features-widget',
                    'location' => 'footer_top',
                    'order' => 2,
                    'feature_title' => '100% Secure Payment',
                    'feature_secondary_title' => 'Pay with confidence on our site',
                    'feature_icon' => '202401150154391.png',
                    'site_info_name' => null,
                    'site_info_description' => null,
                    'site_info_address' => null,
                    'site_info_phone' => null,
                    'site_info_email' => null,
                    'site_info_hours' => null,
                    'newsletter_title' => null,
                    'newsletter_text' => null,
                    'quick_links_title' => null,
                    'quick_links_menu' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'name' => 'site-features-widget',
                    'location' => 'footer_top',
                    'order' => 3,
                    'feature_title' => '24/7 Dedicated Support',
                    'feature_secondary_title' => 'Get in touch with any query you have',
                    'feature_icon' => '202401150155013.png',
                    'site_info_name' => null,
                    'site_info_description' => null,
                    'site_info_address' => null,
                    'site_info_phone' => null,
                    'site_info_email' => null,
                    'site_info_hours' => null,
                    'newsletter_title' => null,
                    'newsletter_text' => null,
                    'quick_links_title' => null,
                    'quick_links_menu' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'name' => 'site-features-widget',
                    'location' => 'footer_top',
                    'order' => 1,
                    'feature_title' => 'Daily Offers',
                    'feature_secondary_title' => 'Exciting discounts, promotions and offers',
                    'feature_icon' => '202401150154531.png',
                    'site_info_name' => null,
                    'site_info_description' => null,
                    'site_info_address' => null,
                    'site_info_phone' => null,
                    'site_info_email' => null,
                    'site_info_hours' => null,
                    'newsletter_title' => null,
                    'newsletter_text' => null,
                    'quick_links_title' => null,
                    'quick_links_menu' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 7,
                    'name' => 'custom-menu-widget',
                    'location' => 'footer',
                    'order' => 2,
                    'feature_title' => null,
                    'feature_secondary_title' => null,
                    'feature_icon' => null,
                    'site_info_name' => null,
                    'site_info_description' => null,
                    'site_info_address' => null,
                    'site_info_phone' => null,
                    'site_info_email' => null,
                    'site_info_hours' => null,
                    'newsletter_title' => null,
                    'newsletter_text' => null,
                    'quick_links_title' => 'Help Centre',
                    'quick_links_menu' => '3',
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 8,
                    'name' => 'custom-menu-widget',
                    'location' => 'footer',
                    'order' => 1,
                    'feature_title' => null,
                    'feature_secondary_title' => null,
                    'feature_icon' => null,
                    'site_info_name' => null,
                    'site_info_description' => null,
                    'site_info_address' => null,
                    'site_info_phone' => null,
                    'site_info_email' => null,
                    'site_info_hours' => null,
                    'newsletter_title' => null,
                    'newsletter_text' => null,
                    'quick_links_title' => 'Useful Links',
                    'quick_links_menu' => '2',
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 9,
                    'name' => 'custom-menu-widget',
                    'location' => 'footer',
                    'order' => 3,
                    'feature_title' => null,
                    'feature_secondary_title' => null,
                    'feature_icon' => null,
                    'site_info_name' => null,
                    'site_info_description' => null,
                    'site_info_address' => null,
                    'site_info_phone' => null,
                    'site_info_email' => null,
                    'site_info_hours' => null,
                    'newsletter_title' => null,
                    'newsletter_text' => null,
                    'quick_links_title' => 'Business',
                    'quick_links_menu' => '4',
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 10,
                    'name' => 'newsletter-widget',
                    'location' => 'footer',
                    'order' => 4,
                    'feature_title' => null,
                    'feature_secondary_title' => null,
                    'feature_icon' => null,
                    'site_info_name' => null,
                    'site_info_description' => null,
                    'site_info_address' => null,
                    'site_info_phone' => null,
                    'site_info_email' => null,
                    'site_info_hours' => null,
                    'newsletter_title' => 'Newsletter Sign Up',
                    'newsletter_text' => 'Sign Up for our monthly newsletter and be the first to know about exciting offers, promotions and new items',
                    'quick_links_title' => null,
                    'quick_links_menu' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 11,
                    'name' => 'site-info-widget',
                    'location' => 'footer',
                    'order' => 0,
                    'feature_title' => null,
                    'feature_secondary_title' => null,
                    'feature_icon' => null,
                    'site_info_name' => null,
                    'site_info_description' => 'This is a description text; now, please provide your version.',
                    'site_info_address' => '959 Homestead Street Eastlake, NYC',
                    'site_info_phone' => '0000-0000-0000',
                    'site_info_email' => 'support@yoursite.com',
                    'site_info_hours' => '9AM - 5PM (GMT +6)',
                    'newsletter_title' => null,
                    'newsletter_text' => null,
                    'quick_links_title' => null,
                    'quick_links_menu' => null,
                    'text_title' => null,
                    'text_content' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            ]);
        }
    }
}
